const HOURLY_WAGE = 3.75
const EVENING_COMPENSATION = HOURLY_WAGE + 1.15
const REGULAR_WORK_HOUR_START = 6;
const REGULAR_WORK_HOUR_END = 18;

const OVERTIME_THRESHOLD = 8;
const OVERTIME_RATE_2 = 1.25;
const OVERTIME_RATE_4 = 1.5;
const OVERTIME_RATE_4_PLUS = 2;
const OVERTIME_INTERVAL = 2;

exports.OVERTIME_THRESHOLD = OVERTIME_THRESHOLD
exports.OVERTIME_RATE_2 = OVERTIME_RATE_2
exports.OVERTIME_RATE_4 = OVERTIME_RATE_4
exports.OVERTIME_RATE_4_PLUS = OVERTIME_RATE_4_PLUS
exports.OVERTIME_INTERVAL = OVERTIME_INTERVAL
exports.HOURLY_WAGE = HOURLY_WAGE
exports.EVENING_COMPENSATION = EVENING_COMPENSATION
exports.REGULAR_WORK_HOUR_START = REGULAR_WORK_HOUR_START
exports.REGULAR_WORK_HOUR_END = REGULAR_WORK_HOUR_END